apiVersion: v1
kind: Service
metadata:
  name: voice-app-webapp 
  labels:
    app: voice-app
    app.kubernetes.io/instance: voice-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: voice-app
    app.kubernetes.io/version: "1.0.1"
    helm.sh/chart: voice-app-0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: webapp,app.kubernetes.io/instance: voice-app,app.kubernetes.io/name: voice-app