apiVersion: v2
name: voice-app
description: A Helm chart for the voice Web Application
version: 0.1.1
appVersion: "1.0.1"
dependencies:
  - name: redis
    version: 17.11.3
    repository: https://charts.helm.sh/stable
