apiVersion: v2
name: voice-app
description: A Helm chart for the voice Web Application
version: 0.1.0
appVersion: "1.0.1"
dependencies:
  - name: redis
    version: 17.8.4
    repository: https://charts.bitnami.com/bitnami
