webapp:
  image:
    repository: abhikgho/text_to_speech_web_app
    tag: web-v1.0.3
  replicaCount: 1

worker:
  image:
    repository: abhikgho/text_to_speech_web_app
    tag: worker-v1.0.3
  replicaCount: 1

ingress:
  enabled: true
  host: voice.app.com

service:
  type: ClusterIP
  port: 5000

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: standard
  auth:
    enabled: false
  replica:
    persistence:
      enabled: true
      storageClass: standard
    replicaCount: 2

persistence:
  uploads:
    enabled: true
    size: 5Gi
    storageClass: standard
    accessMode: ReadWriteOnce
  output:
    enabled: true
    size: 5Gi
    storageClass: standard
    accessMode: ReadWriteOnce