webapp:
  image:
    repository: abhikgho/text_to_speech_web_app
    tag: webapp-v1.0.3
  replicaCount: 1

worker:
  image:
    repository: abhikgho/text_to_speech_web_app
    tag: worker-v1.0.3
  replicaCount: 1

ingress:
  enabled: true
  host: voice.app.com

service:
  type: ClusterIP
  port: 80

redis:
  enabled: true
  master:
    persistence:
      enabled: false

configMap:
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"
